name: ci

on: [push, pull_request]

env:
  CI: "true"
  SIMPLECOV: "true"

jobs:
  rspec-test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Create local database
        env:
          RAILS_ENV: test
        run: |
          gem install bundler -v 2.1.3
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Build and test with rspec
        env:
          RAILS_ENV: test
        run: bundle exec rspec
      - run: ./.github/upload_coverage.sh $GITHUB_EVENT_PATH
